version: '3.5'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./public:/var/www/app/public
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php

    php:
        container_name: login-app
        build:
            context: docker/php
        tty: true
        user: ${C_USER}
        volumes:
            - .:/var/www/app
            - ./docker/php/php-ini-extra.ini:/usr/local/etc/php/conf.d/docker-php-ext-php-ini-extra.ini
            - ~/.ssh:/home/docker/.ssh
        environment:
            DB_NAME: picodi
            DB_HOST: mysql
            DB_USER: root
            DB_PORT: 3306
            DB_PASSWORD: root
        networks:
            - default

    mysql:
        build: ./docker/mysql
        ports:
            - "3306:3306"
        volumes:
            - mysql:/var/lib/mysql
            - ./docker/mysql/docker.conf:/etc/mysql/conf.d/docker.conf
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_DATABASE: symfony
            MYSQL_PASSWORD: root
        networks:
            - default

    adminer:
        image: adminer
        ports:
            - 8081:8080
        environment:
            COLUMNS: 209
            LINES: 20
            ADMINER_DEFAULT_SERVER: mysql

volumes:
    mysql:
